import type { OrganizerEmail } from "@/types/email";

export const DEMO_OWNER = {
  name: "Sacha",
  email: "sacha@demo.example",
} as const;

const OWNER_RECIPIENT = [DEMO_OWNER.email];

/**
 * Jeu de données fictif couvrant chaque dossier de la messagerie.
 * Le domaine réservé `.example` empêche toute confusion avec de vraies adresses.
 */
export const DEMO_EMAILS: OrganizerEmail[] = [
  {
    id: "demo-1",
    senderName: "Sophie Martin",
    sender: "sophie.martin@northstar.example",
    recipients: OWNER_RECIPIENT,
    cc: [],
    bcc: [],
    subject: "Validation du lancement de septembre",
    preview:
      "Peux-tu confirmer les derniers éléments avant notre point de cet après-midi ?",
    body: "Bonjour Sacha,\n\nPeux-tu confirmer les derniers éléments avant notre point de cet après-midi ? Le calendrier de lancement est prêt et l'équipe attend seulement ta validation sur les trois priorités.\n\nMerci,\nSophie",
    receivedAt: "09:42",
    timestamp: 1_784_619_720_000,
    category: "professional",
    folder: "inbox",
    direction: "incoming",
    isRead: false,
    isStarred: true,
  },
  {
    id: "demo-2",
    senderName: "GitHub",
    sender: "notifications@github.example",
    recipients: OWNER_RECIPIENT,
    cc: [],
    bcc: [],
    subject: "Nouvelle activité sur votre dépôt",
    preview:
      "Un nouveau déploiement a été associé à la branche principale de votre projet.",
    body: "Une nouvelle activité a été détectée sur le dépôt app-trie-email. Le déploiement associé à la branche principale est maintenant disponible.",
    receivedAt: "09:18",
    timestamp: 1_784_618_280_000,
    category: "notification",
    folder: "inbox",
    direction: "incoming",
    isRead: false,
    isStarred: false,
  },
  {
    id: "demo-3",
    senderName: "Product Notes",
    sender: "edition@product-notes.example",
    recipients: OWNER_RECIPIENT,
    cc: [],
    bcc: [],
    subject: "7 idées pour mieux planifier votre semaine",
    preview:
      "Cette semaine : une méthode simple pour réduire les tâches en attente.",
    body: "Bonjour,\n\nDans cette édition, découvrez sept idées simples pour mieux planifier votre semaine et garder du temps pour les tâches importantes.\n\nBonne lecture !",
    receivedAt: "08:31",
    timestamp: 1_784_615_460_000,
    category: "newsletter",
    folder: "inbox",
    direction: "incoming",
    isRead: true,
    isStarred: false,
  },
  {
    id: "demo-4",
    senderName: "Maison & Co",
    sender: "offres@maison-co.example",
    recipients: OWNER_RECIPIENT,
    cc: [],
    bcc: [],
    subject: "Votre offre de bienvenue expire dimanche",
    preview:
      "Profitez de 25 % de réduction sur votre première commande avant dimanche.",
    body: "Votre offre de bienvenue expire bientôt. Profitez de 25 % de réduction sur votre première commande avant dimanche soir.",
    receivedAt: "Hier",
    timestamp: 1_784_541_600_000,
    category: "promotion",
    folder: "inbox",
    direction: "incoming",
    isRead: true,
    isStarred: false,
  },
  {
    id: "demo-5",
    senderName: "Papa",
    sender: "famille@messages.example",
    recipients: OWNER_RECIPIENT,
    cc: [],
    bcc: [],
    subject: "Déjeuner samedi",
    preview:
      "Est-ce que midi te convient toujours ? Je réserve la table demain matin.",
    body: "Salut,\n\nEst-ce que midi te convient toujours pour samedi ? Je réserve la table demain matin. Dis-moi si tu préfères un autre horaire.\n\nÀ bientôt !",
    receivedAt: "Hier",
    timestamp: 1_784_535_000_000,
    category: "personal",
    folder: "inbox",
    direction: "incoming",
    isRead: false,
    isStarred: true,
  },
  {
    id: "demo-6",
    senderName: "Facturation Cloud",
    sender: "billing@cloud-suite.example",
    recipients: OWNER_RECIPIENT,
    cc: [],
    bcc: [],
    subject: "Facture de juillet disponible",
    preview:
      "Votre facture mensuelle est disponible dans votre espace professionnel.",
    body: "Bonjour,\n\nVotre facture mensuelle est maintenant disponible dans votre espace professionnel. Aucun paiement supplémentaire n'est requis.\n\nL'équipe Facturation Cloud",
    receivedAt: "Lun.",
    timestamp: 1_784_486_000_000,
    category: "professional",
    folder: "inbox",
    direction: "incoming",
    isRead: true,
    isStarred: false,
  },
  {
    id: "demo-7",
    senderName: "Agenda",
    sender: "reminders@calendar.example",
    recipients: OWNER_RECIPIENT,
    cc: [],
    bcc: [],
    subject: "Rappel : réunion produit dans 30 minutes",
    preview:
      "Votre réunion produit commence aujourd'hui à 14 h dans la salle virtuelle.",
    body: "Rappel : votre réunion produit commence aujourd'hui à 14 h. Vous pouvez rejoindre la salle virtuelle depuis votre calendrier.",
    receivedAt: "Lun.",
    timestamp: 1_784_483_000_000,
    category: "notification",
    folder: "inbox",
    direction: "incoming",
    isRead: false,
    isStarred: false,
  },
  {
    id: "demo-8",
    senderName: "Service inconnu",
    sender: "contact@account-alert.example",
    recipients: OWNER_RECIPIENT,
    cc: [],
    bcc: [],
    subject: "ACTION IMMÉDIATE REQUISE",
    preview:
      "Votre compte sera suspendu. Confirmez immédiatement vos informations.",
    body: "Votre compte sera suspendu. Confirmez immédiatement vos informations personnelles depuis le lien indiqué dans ce message.",
    receivedAt: "Dim.",
    timestamp: 1_784_400_000_000,
    category: "spam",
    folder: "inbox",
    direction: "incoming",
    isRead: true,
    isStarred: false,
  },
  {
    id: "demo-9",
    senderName: "Camille Durand",
    sender: "camille@studio-orbite.example",
    recipients: OWNER_RECIPIENT,
    cc: [],
    bcc: [],
    subject: "Quelques ressources après notre échange",
    preview:
      "Voici les ressources dont nous avons parlé. Je reste disponible si nécessaire.",
    body: "Bonjour Sacha,\n\nVoici les ressources dont nous avons parlé pendant notre échange. Je reste disponible si tu as besoin d'informations complémentaires.\n\nBonne journée,\nCamille",
    receivedAt: "Ven.",
    timestamp: 1_784_220_000_000,
    category: "other",
    folder: "inbox",
    direction: "incoming",
    isRead: false,
    isStarred: false,
  },
  {
    id: "demo-sent-1",
    senderName: DEMO_OWNER.name,
    sender: DEMO_OWNER.email,
    recipients: ["sophie.martin@northstar.example"],
    cc: [],
    bcc: [],
    subject: "Re: Planning de la semaine",
    preview: "Merci Sophie, le planning me convient. Je valide les trois étapes.",
    body: "Bonjour Sophie,\n\nMerci, le planning me convient. Je valide les trois étapes proposées.\n\nBonne journée,\nSacha",
    receivedAt: "Hier",
    timestamp: 1_784_537_000_000,
    category: "professional",
    folder: "sent",
    direction: "outgoing",
    isRead: true,
    isStarred: false,
  },
  {
    id: "demo-draft-1",
    senderName: DEMO_OWNER.name,
    sender: DEMO_OWNER.email,
    recipients: ["contact@association.example"],
    cc: [],
    bcc: [],
    subject: "Proposition de rendez-vous",
    preview: "Bonjour, je souhaiterais vous proposer un échange la semaine prochaine…",
    body: "Bonjour,\n\nJe souhaiterais vous proposer un échange la semaine prochaine au sujet de notre projet.\n\n",
    receivedAt: "Brouillon",
    timestamp: 1_784_608_000_000,
    category: "other",
    folder: "drafts",
    direction: "outgoing",
    isRead: true,
    isStarred: false,
  },
  {
    id: "demo-archive-1",
    senderName: "Équipe Formation",
    sender: "bonjour@formation.example",
    recipients: OWNER_RECIPIENT,
    cc: [],
    bcc: [],
    subject: "Votre attestation est disponible",
    preview: "Votre attestation de participation peut maintenant être téléchargée.",
    body: "Bonjour Sacha,\n\nVotre attestation de participation peut maintenant être téléchargée depuis votre espace.\n\nCordialement,\nL'équipe Formation",
    receivedAt: "12 juil.",
    timestamp: 1_783_944_000_000,
    category: "professional",
    folder: "archive",
    direction: "incoming",
    isRead: true,
    isStarred: false,
  },
  {
    id: "demo-trash-1",
    senderName: "Jeu Concours",
    sender: "gagnant@concours.example",
    recipients: OWNER_RECIPIENT,
    cc: [],
    bcc: [],
    subject: "Vous avez été sélectionné",
    preview: "Réclamez immédiatement votre cadeau exclusif.",
    body: "Vous avez été sélectionné pour recevoir un cadeau. Répondez immédiatement avec vos informations personnelles.",
    receivedAt: "10 juil.",
    timestamp: 1_783_773_000_000,
    category: "spam",
    folder: "trash",
    direction: "incoming",
    isRead: true,
    isStarred: false,
  },
];

export const DEMO_EMAIL_IDS = new Set(DEMO_EMAILS.map((email) => email.id));

export function findDemoEmail(emailId: string) {
  return DEMO_EMAILS.find((email) => email.id === emailId);
}
